/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2;

/**
 *
 * @author Valery
 */
import proyecto2.PantallaAgregarDepartamento;
public class PantallaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName());

    /**
     * Creates new form PantallaDepartamentos
     */
    private Departamento[] listaDepartamentos;
    
    public PantallaPrincipal() {
        this.listaDepartamentos = new Departamento[20]; // Capacidad inicial de 20 departamentos
        initComponents();
        cargarTablaDepartamentos();
        this.btnEliminarDepartamento.addActionListener(evt -> eliminarUltimoDepartamento());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDepartamentos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnNuevoDepartamento = new javax.swing.JButton();
        btnTrasladoArticulos = new javax.swing.JButton();
        btnEliminarDepartamento = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabelMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaDepartamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDepartamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDepartamentosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaDepartamentos);
        if (tablaDepartamentos.getColumnModel().getColumnCount() > 0) {
            tablaDepartamentos.getColumnModel().getColumn(0).setResizable(false);
            tablaDepartamentos.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 500, 240));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Acciones");

        btnNuevoDepartamento.setBackground(new java.awt.Color(51, 204, 0));
        btnNuevoDepartamento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNuevoDepartamento.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoDepartamento.setText("Nuevo Departamento");
        btnNuevoDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoDepartamentoActionPerformed(evt);
            }
        });

        btnTrasladoArticulos.setBackground(new java.awt.Color(0, 153, 204));
        btnTrasladoArticulos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTrasladoArticulos.setForeground(new java.awt.Color(255, 255, 255));
        btnTrasladoArticulos.setText("Traslado Artículos");
        btnTrasladoArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrasladoArticulosActionPerformed(evt);
            }
        });

        btnEliminarDepartamento.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminarDepartamento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarDepartamento.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarDepartamento.setText("Eliminar Departamento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevoDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTrasladoArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNuevoDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTrasladoArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 220, 240));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel5.setText("Gestión de Tienda Valery ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 260, -1));
        getContentPane().add(jLabelMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 520, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoDepartamentoActionPerformed
                     // TODO add your handling code here:
        PantallaAgregarDepartamento pantallaAgregarDepartamento = new PantallaAgregarDepartamento(this.listaDepartamentos);
        pantallaAgregarDepartamento.setVisible(true);
        // agregar evento para cuando se cierre la ventana de pantallaAgregarDepartamento para refrescar la tabla de departamentos
        pantallaAgregarDepartamento.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                cargarTablaDepartamentos();
            }
        });
    }//GEN-LAST:event_btnNuevoDepartamentoActionPerformed

    private void tablaDepartamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDepartamentosMouseClicked
        // TODO add your handling code here:
        System.out.println("Fila seleccionada: " + tablaDepartamentos.getSelectedRow());
        int cantidadArticulos = contarArticulos();
        ListaArticulos listaArticulos = new ListaArticulos(this.listaDepartamentos[tablaDepartamentos.getSelectedRow()], cantidadArticulos);
        listaArticulos.setVisible(true);
        // agregar evento para cuando se cierre la ventana de listaArticulos para refrescar la tabla de departamentos
        listaArticulos.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                cargarTablaDepartamentos();
            }
        });
    }//GEN-LAST:event_tablaDepartamentosMouseClicked

    private void btnTrasladoArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrasladoArticulosActionPerformed
            // TODO add your handling code here:
        PantallaTraslado pantallaTraslado = new PantallaTraslado(this.listaDepartamentos);
        pantallaTraslado.setVisible(true);
    }//GEN-LAST:event_btnTrasladoArticulosActionPerformed

    public void cargarTablaDepartamentos() {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) this.tablaDepartamentos.getModel();
        modelo.setRowCount(0);
        if (this.listaDepartamentos == null) return;
        for (Departamento d : this.listaDepartamentos) {
            if (d != null) {
                modelo.addRow(new Object[]{d.getId(), d.getNombre()});
            }
        }
    }

    private void eliminarUltimoDepartamento() {
        if (this.listaDepartamentos == null) return;
        int ultimoIndex = -1;
        for (int i = this.listaDepartamentos.length - 1; i >= 0; i--) {
            if (this.listaDepartamentos[i] != null) {
                ultimoIndex = i;
                break;
            }
        }
        if (ultimoIndex == -1) {
            this.jLabelMensaje.setText("No hay departamentos para eliminar.");
            this.jLabelMensaje.setForeground(new java.awt.Color(255, 0, 0));
            return;
        }
        Departamento ultimo = this.listaDepartamentos[ultimoIndex];
        if (ultimo.tieneArticulos()) {
            this.jLabelMensaje.setText("No se puede eliminar el departamento '" + ultimo.getNombre() + "' porque tiene artículos asociados.");
            this.jLabelMensaje.setForeground(new java.awt.Color(255, 0, 0));
            return;
        }
        // Eliminar (LIFO)
        this.listaDepartamentos[ultimoIndex] = null;
        this.jLabelMensaje.setText("Departamento eliminado correctamente.");
        this.jLabelMensaje.setForeground(new java.awt.Color(0, 153, 0));
        cargarTablaDepartamentos();
    }
    public int contarArticulos(){
        int contador = 0;
        for (Departamento d : this.listaDepartamentos) {
            if (d != null) {
                for (Articulo a : d.getArticulos()) {
                    if (a != null) {
                        contador++;
                    }
                }
            }
        }
        return contador;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PantallaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarDepartamento;
    private javax.swing.JButton btnNuevoDepartamento;
    private javax.swing.JButton btnTrasladoArticulos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDepartamentos;
    // End of variables declaration//GEN-END:variables
}
